[project]
name = "cashflow-flet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.0",
    "asyncpg>=0.30.0",
    "fastapi>=0.115.6",
    "flet>=0.25.2",
    "sqlalchemy>=2.0.36",
]
